[build]
  builder = "NIXPACKS"
  buildCommand = "cd backend && npm install && npm run build"

[deploy]
  startCommand = "cd backend && npm start"
  healthcheckPath = "/health"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"

[[services]]
  name = "trendy-games-backend"